### ISSUE TITLE
Avatar color and placement

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#1]
- both users should see both avatars (a sphere with the color of the user)
- each user should see his avatar i n the bottom left of his screen
- each user should see his collaborator's avatar in the top right of the screen, smaller because it is more distant

Params to explose to designer:
- Avatar size
- Avatar distance from center of round

Automatically calcualted
- Avatar angle along circle based on number of collaborators (2 = 180 degrees apart, 3 = 120 degrees apart)
- Ones own avatar is always in the "bottom left"; in a 2 person collabo, the 2nd user's avatar would be in the top right

![image](https://user-images.githubusercontent.com/518356/101094848-e84eff80-3571-11eb-8492-17dff01481e0.png)

**Comment by simonadcock** [comment]
A fix for this is in the dev branch.

Given the space available it made more sense to have the avatars positioned on top of each other on the right. If they are placed as described in the issue they are more likely to appear off the screen or the round size has to be decreased in order to make room. This way the (vertical) space available to the round is maximised. I'm happy to update to the algorithm described in the issue but maybe it's worth a chat first.
