### ISSUE TITLE
MVP - FX on/off state not stored with project

### ISSUE THREAD

**Issue by deerwolf** [irllabs/roundaround#143]
When I turn any of the FX on / off their state should be stored with the project and recalled when the project is reopened. Currently these are not stored at all.

**Comment by batchku** [comment]
This is not resolved.

Now, the state of an effect (whether it is on/locked) is saved, but it is not actually applied to the signal chain.

Steps to reproduce:
1.  Create new project
2.  Add steps to first layer
3. Turn on and lock the low-pass filter
4. save and name project
5. close rounds
6. open project
7. press play

Expected behavior:
- UI should show that low-pass filter is on
- playback should apply low-pass filter to the beat

Actual behavior:
- UI shows that low-pass filter is on
- Playback DOES NOT apply low-pass filter
