### ISSUE TITLE
UI update irregularities after mute/unmute

### ISSUE THREAD

**Issue by muganwas** [irllabs/roundaround#268]
When a layer is is clicked or when the mute button is clicked, the layers don't always grey out.

**Comment by mericda** [comment]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/19254822/156642485-fb2cd4c4-ce4c-410c-b08b-a7ff07e1f92d.png">

@muganwas tested this on https://roundaround-dev--pr269-bug-268-ui-update-ir-mrgitv0p.web.app/ , and steps are still not being grayed out when a layer gets muted, and all steps get color when I hit play.  Since mute = playback disabled for that layer, everything should be grayed out within that layer, and we should even disable the momentary animation of step border becoming white, if that layer is grayed out. 

![CleanShot 2022-03-03 at 11 56 24](https://user-images.githubusercontent.com/19254822/156642980-c7f1e099-33ec-4ade-aa7d-58b6cea00b13.gif)

**Comment by muganwas** [comment]
> <img alt="image" width="573" src="https://user-images.githubusercontent.com/19254822/156642485-fb2cd4c4-ce4c-410c-b08b-a7ff07e1f92d.png">
> 
> @muganwas tested this on https://roundaround-dev--pr269-bug-268-ui-update-ir-mrgitv0p.web.app/ , and steps are still not being grayed out when a layer gets muted, and all steps get color when I hit play. Since mute = playback disabled for that layer, everything should be grayed out within that layer, and we should even disable the momentary animation of step border becoming white, if that layer is grayed out.
> 
> ![CleanShot 2022-03-03 at 11 56 24](https://user-images.githubusercontent.com/19254822/156642980-c7f1e099-33ec-4ade-aa7d-58b6cea00b13.gif)

On it. I initially had the idea that this issue was only related to the layer background color.
