### ISSUE TITLE
Gain slider in settings does not allow user to reduce volume to 0

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#31]
all the way down, I still hear the layer:

![image](https://user-images.githubusercontent.com/518356/102916020-af4ed000-4437-11eb-834f-a6780d308aa2.png)

**Comment by batchku** [comment]
Still not down to -96dB

**Comment by simonadcock** [comment]
Do you mean you can still hear it or the label says -48? The slider goes down to -48dB, but when it hits -48 I update the audio to be -96dB (ie. off). This is so that we don't use the limited slider space for values between -48 and -96. I've updated the bottom label to read -96 in case it was confusing.
