### ISSUE TITLE
New layers are added from the inside outwards, not to the outside

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#46]
Newly created layers by a user, or any of multiple users in a collabo should be added after the outermost layer/circle.

**Comment by simonadcock** [comment]
This is due to loading an old round which is not compatible with this version. I have had to change the data structure slightly (eg. include a createdAt date for layers so that ordering is maintained across devices). 

I've now added a filter so that old rounds should no longer appear in the rounds menu.
