### ISSUE TITLE
Incorrect rendering of an inner layer

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#47]
This is with a user that is already logged in; have not seen it consistently
Persists after empty cache and hard reload
Does not happen if I use an incognito window to create a new account and log in

![image](https://user-images.githubusercontent.com/518356/103447987-adf78180-4c47-11eb-92f5-7234d0c9f9db.png)

**Comment by simonadcock** [comment]
This is due to loading an old round which is not compatible with this version. I have had to change the data structure slightly (eg. include a createdAt date for layers so that ordering is maintained across devices). 

I've now added a filter so that old rounds should no longer appear in the rounds menu.
