### ISSUE TITLE
Setup staging server for in-review tasks

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#6]
use the `in-review` for revising tasks that have been fixed but need to be tested
create a staging server on firebase
deploy updates to staging, once reviewed, to production

**Comment by simonadcock** [comment]
I've created a stage version of hosting that we can deploy to. The URL is https://roundaround-stage.web.app

Note that the app will still use the production database, at some point we should probably duplicate the entire Firebase project so that we have a dev and production project. For now though I think this is enough as it means we always have a working site and we don't have two Firebase projects to configure and maintain.
