### ISSUE TITLE
User has the ability to set the over-all timing of a layer to be "ahead" or "behind" the "master clock" 

### ISSUE THREAD

**Issue by batchku** [irllabs/roundaround#70]
- new "delay" parameter introduced in the layer inspector; units are in miliseconds
- default delay is 0
- horizontal slider allows delays up to +/- 100ms
- positive delays mean the steps in the layer occur after the "master" clock
- negative delay mean the steps in the layer occur before the "master" clock
- changing the delay parameter of a step rotates the layer's visualization so that steps in the visualization are proportionally radially displaced

**Comment by simonadcock** [comment]
I've added a "time offset" parameter, which let's you move the layer +/- one step forwards or backwards. 

It seemed to make more sense to use a musical time unit rather than ms so that the musical feel is maintained when changing tempo etc. It also seems logical from a UX point of view that you can move a step forwards and backwards to the next / previous step.

I've called the parameter "time offset" only because I find the concept of negative delays a bit confusing, obviously it's easy to change that to anything else if you prefer.
