### ISSUE TITLE
Fullscreen warning

### ISSUE THREAD

**Issue by deerwolf** [irllabs/roundaround#93]
I get this error a lot in Fullscreen seems to be triggered by menus in the instrument editor. 

![IMG_0069](https://user-images.githubusercontent.com/593435/111853671-42818f80-88d9-11eb-85ad-d75661c56e80.PNG)

**Comment by simonadcock** [comment]
It doesn't look like there's much we can do about this. 

In order to recreate this you need to launch Safari and press the fullscreen button (in the RoundAround menu). Then quickly turn on and off some steps, this makes Safari think we're "typing" on a fake keyboard and shows the warning.

This does not happen in Chrome. This also seems to not happen if you add the page to the homescreen and launch from the homescreen (which will automatically be in fullscreen), although some reports are that it might still happen.

https://stackoverflow.com/questions/53480608/can-i-suppress-alert-it-looks-like-you-are-typing-while-in-full-screen-over-io
